import configparser
from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class QualitySensorsTest(unittest.TestCase):
    def test_canonical_sensor_lock_is_generated_and_fully_pinned(self):
        source = (ROOT / "requirements-dev.in").read_text()
        lock = (ROOT / "requirements.txt").read_text()
        compatibility = (ROOT / "requirements-dev.txt").read_text()

        self.assertIn("mypy==2.3.1", source)
        self.assertIn("pytest==9.1.1", source)
        self.assertIn("ruff==0.16.6", source)
        self.assertIn("autogenerated by uv", lock)
        self.assertIn("mypy==2.3.1", lock)
        self.assertIn("pytest==9.1.1", lock)
        self.assertIn("ruff==0.16.6", lock)
        self.assertEqual(compatibility.strip().splitlines()[-1], "-r requirements.txt")

        for line in lock.splitlines():
            stripped = line.strip()
            if stripped and not stripped.startswith("#"):
                self.assertRegex(stripped, r"^[a-z0-9][a-z0-9-]*==[^=\s]+$")

    def test_mypy_scope_is_strict_and_bound_to_guardrail_hooks(self):
        parser = configparser.ConfigParser()
        parser.read(ROOT / "mypy.ini")
        mypy = parser["mypy"]
        self.assertEqual(mypy.get("strict"), "True")
        self.assertEqual(mypy.get("python_version"), "3.11")
        files = {item.strip() for item in mypy.get("files", "").split(",")}
        self.assertEqual(
            files,
            {
                ".cursor/hooks/feedback_check.py",
                ".cursor/hooks/guard_shell.py",
            },
        )

    def test_makefile_and_ci_enforce_typecheck(self):
        makefile = (ROOT / "Makefile").read_text()
        ci = (ROOT / ".github" / "workflows" / "ci.yml").read_text()
        validate = (ROOT / "scripts" / "validate.sh").read_text()

        self.assertIn("typecheck:", makefile)
        self.assertIn("-m mypy --config-file mypy.ini", makefile)
        self.assertIn("make typecheck", validate)
        self.assertGreaterEqual(ci.count("pip install -r requirements.txt"), 2)
        self.assertIn("python -m mypy --config-file mypy.ini", ci)

    def test_runtime_installer_does_not_install_python_dependencies(self):
        installer = (ROOT / "scripts" / "install-local.sh").read_text()
        self.assertNotIn("pip install", installer)
        self.assertNotIn("requirements.txt", installer)
        self.assertNotIn("requirements-dev", installer)


    def test_quality_manifests_are_visible_to_agent_context(self):
        source = (ROOT / "src" / "local-agent").read_text()
        self.assertGreaterEqual(source.count('"requirements-dev.in"'), 2)
        self.assertGreaterEqual(source.count('"mypy.ini"'), 2)


if __name__ == "__main__":
    unittest.main()
